{% set version = "8.0.0" %}

package:
  name: traitsui
  version: {{ version }}

source:
  fn: traitsui-{{ version }}.tar.bz2
  url: https://pypi.io/packages/source/t/traitsui/traitsui-{{ version }}.tar.gz
  sha256: 901b9d1cbc45513e00a7397677b098441b28774b688f30a159bad4801bf40364

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - pyface >=8.0
    - traits >=6.2.0
    - importlib-metadata  # [py<38]

test:
  imports:
    - traitsui
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://docs.enthought.com/traitsui/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: TraitsUI - Traits-capable windowing framework
  description: |
    TraitsUI is a Python user interface toolkit that provides a declarative approach
    to building interactive GUIs. It automatically generates user interfaces from
    declarative object definitions using the Traits type system. TraitsUI supports
    multiple GUI backends including Qt and wxPython, allowing developers to create
    cross-platform desktop applications with minimal code. The framework is
    particularly well-suited for scientific and engineering applications where
    rapid prototyping and data visualization are important.
  doc_url: https://docs.enthought.com/traitsui/index.html
  dev_url: https://github.com/enthought/traitsui

extra:
  recipe-maintainers:
    - grlee77
