{% set version = "6.1.0" %}

package:
  name: traitsui
  version: {{ version }}

source:
  fn: traitsui-{{ version }}.tar.bz2
  url: https://pypi.io/packages/source/t/traitsui/traitsui-{{ version }}.tar.gz
  sha256: e36468072c33aee0b8d031de386864f04ff5ed208c7be1427a19a64a802f1ef8

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - pip
    - python
    - pyface >=6
    - traits
  run:
    - python
    - pyface >=6
    - traits

test:
  imports:
    - traitsui

about:
  home: http://docs.enthought.com/traitsui/
  license: BSD 3-clause
  summary: TraitsUI - Traits-capable windowing framework

extra:
  recipe-maintainers:
    - grlee77
