{% set version = "7.3.1" %}

package:
  name: traitsui
  version: {{ version }}

source:
  fn: traitsui-{{ version }}.tar.bz2
  url: https://pypi.io/packages/source/t/traitsui/traitsui-{{ version }}.tar.gz
  sha256: 9474ad67f345d96b326b401e9a01405c8082c92fa43bf47c0b039818e587ac69

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python >=3.6
    - pyface >=7.3.0
    - traits >=6.2.0

test:
  imports:
    - traitsui
  requires:
    - pip
    # pyface 7.3.0 requires:
    - importlib-metadata
    - importlib_resources
  commands:
    - pip check

about:
  home: http://docs.enthought.com/traitsui/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: TraitsUI - Traits-capable windowing framework
  doc_url: https://docs.enthought.com/traitsui/index.html
  dev_url: https://github.com/enthought/traitsui

extra:
  recipe-maintainers:
    - grlee77
