travis:
  secure:
    BINSTAR_TOKEN: Z2FLSWKiXUXJWOrJ/cVMwhOg/YwFL05XnkBm1LFNvV8SZ87T5afVZpr3io+q2z49S0vzbhO/VDKGzjKG0nqb6LlPIsRlDFVFYrMLY4iIBYLGJIQOcT2xLo3sUbUJ10IciSH2+ikF+0fJ3WR7Xbf2IP7EU0W/e9GPeIVZ0XER1qPlKnVg4vXL9KOCK9MSdRvX60FUnuw/Z298aW8AHxLFp1uqx/8JGKlRQtIpqqG3bOKLzUIL2JfP8++1g8lGAfSFK+i6B7/aawE56jK9W77baMfkJQwUzawGQ3VPkqBqNeefTLWA7z/nR+xnKkIlaUVKGlafxIodxxhvpH5T0KAvXiQMHh4HjLIJpVOkRo6UT8N8vRxQeJbS3jq/spgysBSm/KOur9be5BbfzQP8cReUWD+bH4aTk8MiBg+21cqeytHRg1J2QQ08VvZWvqnxz2W/19UbFitCnSMONMtvg7P35XfKULSZHt5bGYvHq1TvaG/k0hnU1c+pRKRbPGw/AtFCkDWOxi0+0kxK7iszAce7Aimv7zdYnkKm2amE2G+Xysph2qflxeF1PUcDmDRmtkkSS7ynQMDJknn1+Vu6QX55CexFA10aDXOHiVR8MNYCzFiacukBS3vUjKmZN/lWRkseajuCRLeg7vrizbr1uJPfxPyVbvfFGg3l/h8VqM7/B7Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
