travis:
  secure:
    BINSTAR_TOKEN: R9uRlf7krCz1aaD+h+BcvH8Dievhs651+/Z+de8baV+/BzLm+H68BfInQzFC6BtlAUXJbPO69pgcthl5ZS3Y+l50GiDIsig/OFIHWkvddoH2Pr7FaVJl3H/vxtrlmoDuJdXsJ2XIVnoNrvA+7ei4WoYM5Lz2T8uYtH93uRBsXmsM/jJq5C6933RCww3PMvDufIM57TPulFbAVWxDI5QK9Rlg0qhoqJ7jWFqUtMQw8xccLnONQk3/ye4Epzm+NoY47kdEOteHJYmrE4sr7Mk+fezZywMtlEGGudeX2Scr5BDWqPyC5M4kp5YA2uiGiDtBUj7VpMaP8HSrQd0w/07oTDYZjB+16skkM0lg/6fDlvkp5v57dct5L/0PKUR+k1foKsTX7bUEPuJYpw+bUFmV+Gj5HYlkdpF2GqQuwrokMrmvOE92my7meX2JXQLlShOPdybOyM6i/lSGfl4N86f1ENS8QK/NgyYKT6xlaNznlWgbfatYsDVaJMhC7FbS5bHVwIrhVHYaUysPh/uchBnsxkPvzoXbenvuhpptCWpkezEKij3+M7iUQnfCakE+oYSncaPaOKxc3QGZRyEVVUzhNHBFtvc9NTh6DfEcbStiA/FRfGWifX0r9vpmoeBjP87UtpjTZ3Lc/UG6yXO2TZ5/5fB2ikWt8db1wTy7BRqeq5c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
