travis:
  secure:
    BINSTAR_TOKEN: gGhoRnjHUGHoNG1mKDd/o1L7YiU6I+HQHduLjgJZuVLhT6TaecRUo50mkOdZTWkPqO3o9RbuOn78W3DS+JEM4JD9XVqRrbJIanqtDfDlD9YuqWJ1oy92nreXp/YHCQJQ7AbRbDmQnMEdu0YUM2QRBURc0CwEQPyDpxvZAQQT5OVrHUVZuEcSz1oA5x34OQ+wyuWoGI5JnzXo9JQ8M6ikVj8s8nylWs7PIxd8jT4TgCQQhsyZQthjGxED9MEn+8bA/Dhmvuow2tXhzcHj+5ilZnLD+uL8h11de9kWwZ9XdM5hENu1AEklDi76W2ASnj1Uk3uX6YbInEQbOpAz86o29s5976SFAqx0C+r/taVMw/mUfoChWxftCtEYBugKWPYDlVKD2iRUZzMrxVB+AplAjSmjJQj6T85N3ial3M0Pdy78uCZyytY1/OUh0FnGLBaAP/1HJvBpdDAXmtpF1eKMdnD/F04UdGnjHEsiPXAcgyzMOpuE0QPmMY/ui7bey9z2AN6y400ig9AGXN5cY1JiOcWWRnDGt9j7gfoSJNOJ5v7GPUAv3RCdBHZ0MTVO6h0vBfD5YK/iFyl6ASJXGZU4UMrWGcro5gWZWTHwjTYlH/rlIzgNTTN7k3hW76xZjXy6cPvoXdty8VOI3VuR3MWiFiV96tP4N9IBgom/8wi3sRY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
